server:
  servlet:
    context-path: /test-service-one
eureka:
  instance:
    hostname: test-service-one
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name:thatman}
      user.password: ${spring.security.user.password:miamoro1y}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://thatman-eureka:miamoro1y-eureka@localhost:8000/eureka/



spring:
  redis:
    host: 127.0.0.1 # redis 地址
    port: 6379 # redis端口
    database: 0 # 使用的缓存库  共16个（0-15）
    timeout: 2000  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    password: thatman-redis
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 40
        # 最小空闲连接数
        min-idle: 0
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  2000
        # 最大活跃连接数，负数为不限制
        max-active: 80

logging:
  config: classpath:resources/logback-spring.xml

userName : config-userName
userPassword : config-userPassword


