server:
  servlet:
    context-path: /zuul-service
spring:
  security:
    user:
      name: thatman-admin
      password: thatman-admin
zuul:
  routes:
    sina:
      path: /sina1/**
      url: http://www.sina.com.cn
    baidu:
      path: /xxx/**
      url: http://www.baidu.com
    service-one:
      path: /service-one/**
      serviceId: service-one
      stripPrefix: false

