server:
  servlet:
    context-path: /zuul-service
spring:
  security:
    user:
      name: thatman-admin
      password: thatman-admin
zuul:
  routes:
    sina:
      path: /sina/**
      url: http://www.sina.com.cn
    xxx:
      path: /baidu/**
      url: http://www.baidu.com

    service-one:
      path: /service-one/**
      serviceId: service-one
      stripPrefix: false

