spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thatmanmiamoro1y/config.git
          search-paths: config-repo-dev
          basedir: config-repo-dev
          force-pull: true
          default-label: dev
          username: miamoro1y@163.com
          password: miamoro1y
server:
  port: 8001

eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
    metadata-map:
      name: ${spring.security.user.name}
      password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://thatman:miamoro1y@localhost:8000/eureka/