server:
  port: 8001

spring:
  security:
    user:
      name: thatman
      password: miamoro1y
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thatmanmiamoro1y/config-service.git
          search-paths: config-repo-dev
          basedir: F:\MyServer\config-repo\config-repo-dev
          force-pull: false
          default-label: ${spring.profiles.active}
          username: miamoro1y@163.com
          password: miamoro1y
      username: config
      password: config


eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
    metadata-map:
      name: ${spring.security.user.name}
      password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://thatman:miamoro1y@localhost:8000/eureka/