server:
  port: 8001

spring:
  security:
    user:
      name: thatman-config
      password: thatman-config
  profiles:
    active: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thatmanmiamoro1y/config-service.git
          search-paths: config-repo-test
          basedir: F:\MyServer\config-repo
          force-pull: true
          default-label: test
          username: miamoro1y@163.com
          password: miamoro1y
      profile: test
      label: test


eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
    metadata-map:
      name: ${spring.security.user.name}
      password: ${spring.security.user.password}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://thatman-eureka:miamoro1y-eureka@localhost:8000/eureka/